input {
  tcp {
    port => 5044
    codec => json_lines
  }
}

filter {
  if [logger_name] =~ "com.apexpay" {
    mutate {
      add_tag => [ "apexpay-app" ]
    }
  }
}

output {
  elasticsearch {
    hosts => ["elasticsearch:9200"]
    index => "apexpay-logs-%{+YYYY.MM.dd}"
  }
  stdout { codec => rubydebug }
}
