apiVersion: v1
kind: ConfigMap
metadata:
  name: apexpay-config
data:
  postgres-db: "payment_platform"
  postgres-user: "postgres"
  postgres-url: "jdbc:postgresql://apexpay-postgres:5432/payment_platform"
  redis-host: "apexpay-redis"
  redis-port: "6379"
  next-public-api-url: "https://apexpay.local"
