apiVersion: apps/v1
kind: Deployment
metadata:
  name: apexpay-postgres
  labels:
    app: apexpay-postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: apexpay-postgres
  template:
    metadata:
      labels:
        app: apexpay-postgres
    spec:
      containers:
        - name: postgres
          image: postgres:16-alpine
          ports:
            - containerPort: 5432
          env:
            - name: POSTGRES_DB
              valueFrom:
                configMapKeyRef:
                  name: apexpay-config
                  key: postgres-db
            - name: POSTGRES_USER
              valueFrom:
                configMapKeyRef:
                  name: apexpay-config
                  key: postgres-user
            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: apexpay-secrets
                  key: postgres-password
          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data
          resources:
            limits:
              cpu: "1"
              memory: 1Gi
            requests:
              cpu: 500m
              memory: 512Mi
          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - payment_platform
            initialDelaySeconds: 15
            periodSeconds: 10
          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - postgres
                - -d
                - payment_platform
            initialDelaySeconds: 10
            periodSeconds: 5
      volumes:
        - name: postgres-storage
          persistentVolumeClaim:
            claimName: postgres-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: apexpay-postgres
spec:
  selector:
    app: apexpay-postgres
  ports:
    - port: 5432
      targetPort: 5432
  type: ClusterIP
