package com.apexpay.controller;

import com.apexpay.dto.*;
import com.apexpay.security.UserPrincipal;
import com.apexpay.service.AiService;
import io.swagger.v3.oas.annotations.Operation;
import io.swagger.v3.oas.annotations.security.SecurityRequirement;
import io.swagger.v3.oas.annotations.tags.Tag;
import jakarta.validation.Valid;
import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.http.ResponseEntity;
import org.springframework.security.access.prepost.PreAuthorize;
import org.springframework.security.core.annotation.AuthenticationPrincipal;
import org.springframework.web.bind.annotation.*;

import java.util.List;
import java.util.UUID;

@RestController
@RequestMapping("/api/ai")
@PreAuthorize("isAuthenticated()")
@Tag(name = "AI Financial Assistant & Insights", description = "Endpoints for the AI financial assistant, budget suggestions, summaries, and scores.")
@SecurityRequirement(name = "Bearer Authentication")
public class AiController {

    private final AiService aiService;

    @Autowired
    public AiController(AiService aiService) {
        this.aiService = aiService;
    }

    @PostMapping("/chat")
    @Operation(summary = "Submit Prompt to AI Chat", description = "Submits a prompt to the AI chat assistant and receives a financial feedback reply.")
    public ResponseEntity<ApiResponse<ChatResponse>> chat(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @Valid @RequestBody ChatRequest request) {
        ChatResponse response = aiService.chat(userPrincipal.getId(), request);
        return ResponseEntity.ok(ApiResponse.success("AI Chat reply received", response));
    }

    @GetMapping("/chat/history")
    @Operation(summary = "Get Chat History", description = "Retrieves all past messages exchanged with the AI assistant.")
    public ResponseEntity<ApiResponse<List<ChatHistoryResponse>>> getChatHistory(
            @AuthenticationPrincipal UserPrincipal userPrincipal) {
        List<ChatHistoryResponse> history = aiService.getChatHistory(userPrincipal.getId());
        return ResponseEntity.ok(ApiResponse.success("AI Chat history retrieved", history));
    }

    @GetMapping("/insights")
    @Operation(summary = "Get Smart Insights", description = "Retrieves dynamic spending and savings insights generated by the AI engine.")
    public ResponseEntity<ApiResponse<List<FinancialInsightResponse>>> getInsights(
            @AuthenticationPrincipal UserPrincipal userPrincipal) {
        List<FinancialInsightResponse> insights = aiService.getInsights(userPrincipal.getId());
        return ResponseEntity.ok(ApiResponse.success("Smart financial insights retrieved", insights));
    }

    @GetMapping("/summary")
    @Operation(summary = "Get Monthly Financial Summary", description = "Retrieves monthly aggregate statistics, income, expenses, and category breakdown.")
    public ResponseEntity<ApiResponse<FinancialSummaryResponse>> getSummary(
            @AuthenticationPrincipal UserPrincipal userPrincipal) {
        FinancialSummaryResponse summary = aiService.getSummary(userPrincipal.getId());
        return ResponseEntity.ok(ApiResponse.success("Financial summary retrieved", summary));
    }

    @GetMapping("/budget")
    @Operation(summary = "Get Budget Recommendations", description = "Retrieves smart categorical budget suggestions calculated from user spending history.")
    public ResponseEntity<ApiResponse<List<BudgetRecommendationResponse>>> getBudgetRecommendations(
            @AuthenticationPrincipal UserPrincipal userPrincipal) {
        List<BudgetRecommendationResponse> budgets = aiService.getBudgetRecommendations(userPrincipal.getId());
        return ResponseEntity.ok(ApiResponse.success("Budget recommendations retrieved", budgets));
    }

    @PostMapping("/budget/{id}/apply")
    @Operation(summary = "Apply Budget Recommendation", description = "Accepts a budget recommendation and updates the active monthly limits in database.")
    public ResponseEntity<ApiResponse<BudgetRecommendationResponse>> applyBudgetRecommendation(
            @AuthenticationPrincipal UserPrincipal userPrincipal,
            @PathVariable("id") UUID recommendationId) {
        BudgetRecommendationResponse response = aiService.applyBudgetRecommendation(userPrincipal.getId(), recommendationId);
        return ResponseEntity.ok(ApiResponse.success("Budget recommendation applied successfully", response));
    }

    @GetMapping("/health-score")
    @Operation(summary = "Get Financial Health Score", description = "Retrieves user's overall financial health score card based on multiple financial indexes.")
    public ResponseEntity<ApiResponse<FinancialHealthResponse>> getHealthScore(
            @AuthenticationPrincipal UserPrincipal userPrincipal) {
        FinancialHealthResponse response = aiService.getFinancialHealthScore(userPrincipal.getId());
        return ResponseEntity.ok(ApiResponse.success("Financial health score card retrieved", response));
    }
}
